apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-frontend-app
  namespace: argocd
spec:
  project: default
  source:
    # Sustituye con la URL real del repositorio main-frontend-app
    repoURL: https://github.com/Ferremat/main-frontend-app.git
    targetRevision: main
    path: deploy/kubernetes/charts/main-frontend-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ferremat-deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
