enabled: true

app:
  image:
    repository: iferlop/main-frontend-app
    tag: 51-03bd900
    pullPolicy: Always
  containerPort: 3000
  container:
    name: main-frontend-app
    Port: 3000
    replicas: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: ferremat.es
  path: /
  pathType: Prefix

env:
  NUXT_PUBLIC_API_URL: "http://api.ferremat.es/"
